### ISSUE TITLE
A single input for shiny app?

### ISSUE THREAD

**Issue by christophsax** [dsbbfinddx/FIND_Cov_19_Tracker#53]
@pat-s Ideally, I get, `data_shiny.csv`, which the shiny app can download once a day. It should combine JHU and test data:

```r
# A tibble: 18,534 x 8
   country date       cases new_cases deaths new_deaths tests new_tests
   <chr>   <date>     <dbl>     <dbl>  <dbl>      <dbl> <dbl>     <dbl>
 1 CN      2020-01-22   547       547     17         17    NA        NA
 2 JP      2020-01-22     2         2      0          0    NA        NA
 3 TH      2020-01-22     2         2      0          0    NA        NA
 4 MO      2020-01-22     1         1      0          0    NA        NA
 5 KR      2020-01-22     1         1      0          0    NA        NA
 6 TW      2020-01-22     1         1      0          0    56        44
 7 US      2020-01-22     1         1      0          0    24        10
 8 CN      2020-01-23   639        92     18          1    NA        NA
 9 TH      2020-01-23     3         1      0          0    NA        NA
10 HK      2020-01-23     2         2      0          0    NA        NA
```

- Country identifier: `iso2c`, see below for how to match them.
- only `cases`, `deaths`, and `tests` needed,
- `total` and `new`. I guess they are not always identical to `cumsum`?
- Also: `pop`, in 100k, we need to calculate per capita measures.

Here's the code to create the table above. Perhaps include as part of `create_shiny_data()`?

```r
pkgload::load_all(".")
library(tidyverse)

test <- create_shiny_data()$cv_data_countries
jsu <- read_csv("input_data/coronavirus.csv")

iso_country <- 
  countrycode::codelist %>%
  as_tibble() %>%
  select(
    regex = country.name.en.regex, country = iso2c
  )

data <- 
  jsu %>% 
  left_join(test, by = c("date", "country")) %>% 
  select(
    name = country,
    date,
    cases, new_cases, deaths, new_deaths, tests = tests_cumulative, new_tests
  )

data_shiny <- 
  data %>% 
  fuzzyjoin::regex_left_join(iso_country, by = c("name" = "regex"), ignore_case = TRUE) %>% 
  mutate(country = case_when(
    name == "Kosovo"    ~ "XK",
    TRUE                ~ country
  )) %>% 
  # drop
  # 1 Diamond Princess Cruise Ship
  # 2 MS Zaandam  
  filter(!is.na(country)) %>% 
  select(-regex, -name) %>% 
  select(country, everything())

data_shiny
```

**Comment by pat-s** [comment]
@christophsax `FindCovTracker::create_shiny_data()` should mainly do what you requested.
You may need to calculate some additional columns to fit all your needs.

Feel free to tweak the function in the branch directly.

NB: I added {renv} for this project. Please run `renv::init()` when you checkout the branch `r-package`.

**Comment by christophsax** [comment]
@pat-s Could you add `FindCovTracker::create_shiny_data()` to the CI process, so that `data_shiny.csv` is at `https://github.com/dsbbfinddx/data/data_shiny.csv`?

**Comment by pat-s** [comment]
It will be at `dsbbfinddx/data/processed/data_shiny.csv`. Just fixed a minor regression, next build should succeed and write the file.

**Comment by christophsax** [comment]
Klappt dann der 6 Stunden Update? Letzter Commit ist vor 17h.

**Comment by christophsax** [comment]
This works now, thanks @pat-s!
