### ISSUE TITLE
About negative `new_cases` and `new_deaths`

### ISSUE THREAD

**Issue by pat-s** [dsbbfinddx/FIND_Cov_19_Tracker#54]
@christophsax 

This arises from the data.
I've checked some instances where this occurs.

In these cases, the cases count of a day is less than the cases count of the previous day, hence a negative lag is calculated.
The cases count comes directly from the JHU data and these instances are probably related to data quality.

We could account for this by setting these observations to 0 for `new_deaths` and `new_cases`. What do you think?

**Comment by christophsax** [comment]
Probably, but we should it discuss with Anna. Perhaps later in the call.

**Comment by pat-s** [comment]
Did we make a final decision here?

**Comment by christophsax** [comment]
This looks good now, data tweaking is out of scope.
